# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('wea_id', models.AutoField(primary_key=True, serialize=False)),
                ('temperature', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('date_record', models.DateField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Location')),
            ],
        ),
    ]
