# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author_expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.Expert')),
                ('author_farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.Farmer')),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
