# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_db',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
