# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0002_weather'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('crop_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('family', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='CropNutrient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crop.Crop')),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('dis_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=50)),
                ('image', models.FileField(blank=True, null=True, upload_to='diseases/')),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('dis_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='FertiProvide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ferti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crop.Fertilizer')),
            ],
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('nut_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('nut_type', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='SoilNutrient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Location')),
                ('nutrient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crop.Nutrient')),
            ],
        ),
        migrations.AddField(
            model_name='fertiprovide',
            name='nutrient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crop.Nutrient'),
        ),
        migrations.AddField(
            model_name='cropnutrient',
            name='nutrient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crop.Nutrient'),
        ),
        migrations.AlterUniqueTogether(
            name='soilnutrient',
            unique_together=set([('location', 'nutrient')]),
        ),
        migrations.AlterUniqueTogether(
            name='fertiprovide',
            unique_together=set([('ferti', 'nutrient')]),
        ),
        migrations.AlterUniqueTogether(
            name='cropnutrient',
            unique_together=set([('crop', 'nutrient')]),
        ),
    ]
