# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
        ('crop', '0002_auto_20171031_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropFarmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crop.Crop')),
                ('disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crop.Disease')),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.Farmer')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='cropfarmer',
            unique_together=set([('crop', 'disease', 'farmer')]),
        ),
    ]
