# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0003_auto_20171031_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropfarmer',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
